-- DrawUp V20 personal Arch Coach, file 1 of 5: tables.
-- Additive and idempotent. Creates new tables only. Nothing is dropped or rewritten.

-- The 14 skills on the Arch Coach card, in display order.
create or replace function public.arch_coach_skill_keys()
returns text[] language sql immutable as $$
  select array['design','render','space_planning','research','precedents','problem_solving',
    'code_compliance','accessibility','materials','curiosity','details','documentation','advice','presentation']
$$;

-- Starting archetype: College Professor, balanced ratings in the 60s and low 70s (914 points).
create or replace function public.arch_coach_default_skills()
returns jsonb language sql immutable as $$
  select '{"design":66,"render":60,"space_planning":64,"research":72,"precedents":70,"problem_solving":68,"code_compliance":64,"accessibility":62,"materials":62,"curiosity":70,"details":62,"documentation":64,"advice":68,"presentation":62}'::jsonb
$$;

-- Point budget grows with XP but is capped well below 14 x 99 (1386), so maxing every skill is impossible.
create or replace function public.arch_coach_budget(p_xp integer)
returns integer language sql immutable as $$
  select least(1190, 920 + greatest(coalesce(p_xp, 0), 0) / 20)
$$;

create or replace function public.arch_coach_level(p_xp integer)
returns integer language sql immutable as $$
  select 1 + floor(sqrt(greatest(coalesce(p_xp, 0), 0) / 25.0))::integer
$$;

create table if not exists public.arch_coach_legends (
  key text primary key,
  name text not null,
  kind text not null default 'architect',
  principles text[] not null default '{}',
  note text,
  xp_required integer not null default 100,
  sort_order integer not null default 100,
  constraint arch_coach_legends_kind_check check (kind in ('architect', 'engineer'))
);

create table if not exists public.arch_coach_profiles (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  mode text,
  appearance jsonb not null default '{}'::jsonb,
  discipline text not null default 'Architecture',
  focus text not null default 'Design',
  archetype text not null default 'College Professor',
  answer_style text not null default 'balanced',
  skills jsonb not null default public.arch_coach_default_skills(),
  legend text references public.arch_coach_legends(key) on delete set null,
  language text not null default 'auto',
  xp integer not null default 0,
  prompt_answered_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint arch_coach_profiles_mode_check check (mode is null or mode in ('custom', 'generic', 'later')),
  constraint arch_coach_profiles_style_check check (answer_style in ('concise', 'balanced', 'in_depth')),
  constraint arch_coach_profiles_lang_check check (language in ('auto','en','es','fr','pt','zh','ar','hi','de','ja','ko','tl','vi','it')),
  constraint arch_coach_profiles_text_len check (char_length(discipline) <= 60 and char_length(focus) <= 60 and char_length(archetype) <= 60),
  constraint arch_coach_profiles_appearance_check check (jsonb_typeof(appearance) = 'object' and char_length(appearance::text) <= 2000),
  constraint arch_coach_profiles_xp_check check (xp >= 0)
);

-- XP ledger: one row per earning event. The unique key stops the same event from counting twice.
create table if not exists public.arch_coach_xp_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  kind text not null,
  ref_id text not null,
  points integer not null,
  created_at timestamptz not null default now(),
  constraint arch_coach_xp_events_once unique (user_id, kind, ref_id)
);

create index if not exists arch_coach_xp_events_user_idx on public.arch_coach_xp_events (user_id, kind, created_at desc);

select 'DONE drawup-v20-coach-01' as status;
-- END
