import { NextResponse } from 'next/server';
export const runtime='nodejs'; export const dynamic='force-dynamic';
const url=process.env.NEXT_PUBLIC_SUPABASE_URL||''; const anon=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||''; const service=process.env.SUPABASE_SERVICE_ROLE_KEY||'';
async function uid(req:Request){const a=req.headers.get('authorization')||'';if(!a.startsWith('Bearer ')||!url||!anon||!service)return null;const r=await fetch(url+'/auth/v1/user',{headers:{apikey:anon,Authorization:a},cache:'no-store'});if(!r.ok)return null;return (await r.json()).id||null}
async function rest(path:string,init:RequestInit={}){return fetch(url+'/rest/v1/'+path,{...init,cache:'no-store',headers:{apikey:service,Authorization:'Bearer '+service,'Content-Type':'application/json',Prefer:'return=representation',...(init.headers||{})}})}
async function jsonOr<T>(r:Response,fallback:T):Promise<T>{try{return r.ok?await r.json():fallback}catch{return fallback}}
export async function GET(req:Request){const id=await uid(req);if(!id)return NextResponse.json({error:'Unauthorized'},{status:401});const [p,e,c]=await Promise.all([rest('profiles?id=eq.'+id+'&select=*'),rest('profile_education?user_id=eq.'+id+'&select=*&order=created_at.desc'),rest('career_timeline?user_id=eq.'+id+'&select=*&order=start_date.desc.nullslast,created_at.desc')]);return NextResponse.json({profile:(await jsonOr<any[]>(p,[]))[0]||null,education:await jsonOr<any[]>(e,[]),career:await jsonOr<any[]>(c,[])},{headers:{'Cache-Control':'no-store, max-age=0'}})}
// V17: this route writes with the service role, so it must never pass through
// fields a member is not allowed to set on themselves (account_type, is_admin,
// verification flags…). Only these columns are accepted.
const PROFILE_FIELDS=['display_name','username','pronouns','current_location','title','bio','website','linkedin_url','instagram_url','avatar_url','disciplines','credentials','primary_affiliation_type','primary_affiliation_name','onboarding_completed_at','onboarding_interests','discoverable','is_public'];
const EDUCATION_FIELDS=['institution_name','institution_type','program','degree_or_certificate','start_year','graduation_year','status','is_primary','discoverable'];
const CAREER_FIELDS=['role','organization','location','start_date','end_date','description','sort_order'];
function pick(o:any,keys:string[]){const out:any={};if(o&&typeof o==='object')for(const k of keys)if(k in o)out[k]=o[k];return out;}
export async function POST(req:Request){const id=await uid(req);if(!id)return NextResponse.json({error:'Unauthorized'},{status:401});const raw=await req.json();const b={profile:raw?.profile?pick(raw.profile,PROFILE_FIELDS):null,education:(Array.isArray(raw?.education)?raw.education:(raw?.education?[raw.education]:[])).map((x:any)=>pick(x,EDUCATION_FIELDS)),career:(Array.isArray(raw?.career)?raw.career:(raw?.career?[raw.career]:[])).map((x:any)=>pick(x,CAREER_FIELDS))};const errors:string[]=[];
// This route writes with the service role, which the reserved-name trigger (0022) trusts,
// so check reserved handles/names here too.
for(const [k,disp] of [['username',false],['display_name',true]] as const){const v=b.profile?.[k];if(typeof v==='string'&&v.trim()){const r=await rest('rpc/drawup_is_reserved_name',{method:'POST',body:JSON.stringify({p:v,p_is_display:disp})});if(r.ok&&(await r.json())===true)return NextResponse.json({error:`"${v}" is reserved by DrawUp. Please choose another.`},{status:400})}}
if(b.profile&&typeof b.profile==='object'){let r=await rest('profiles?id=eq.'+id,{method:'PATCH',body:JSON.stringify({...b.profile,updated_at:new Date().toISOString()})});if(r.ok){const rows=await jsonOr<any[]>(r,[]);if(!rows.length)r=await rest('profiles',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify({id,...b.profile,updated_at:new Date().toISOString()})})}if(!r.ok)errors.push('profile: '+await r.text())}
for(const x of (Array.isArray(b.education)?b.education:(b.education?[b.education]:[]))){const r=await rest('profile_education',{method:'POST',body:JSON.stringify({...x,user_id:id})});if(!r.ok)errors.push('education: '+await r.text())}
for(const x of (Array.isArray(b.career)?b.career:(b.career?[b.career]:[]))){const r=await rest('career_timeline',{method:'POST',body:JSON.stringify({...x,user_id:id})});if(!r.ok)errors.push('career: '+await r.text())}
if(errors.length)return NextResponse.json({error:errors.join(' | ')},{status:400});return NextResponse.json({ok:true},{headers:{'Cache-Control':'no-store, max-age=0'}})}
