import { NextResponse } from 'next/server';
export const runtime='nodejs'; export const dynamic='force-dynamic';
const url=process.env.NEXT_PUBLIC_SUPABASE_URL||''; const anon=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||''; const service=process.env.SUPABASE_SERVICE_ROLE_KEY||'';
async function uid(req:Request){const a=req.headers.get('authorization')||'';if(!a.startsWith('Bearer ')||!url||!anon||!service)return null;const r=await fetch(url+'/auth/v1/user',{headers:{apikey:anon,Authorization:a}});if(!r.ok)return null;return (await r.json()).id||null}
async function rest(path:string,init:RequestInit={}){return fetch(url+'/rest/v1/'+path,{...init,headers:{apikey:service,Authorization:'Bearer '+service,'Content-Type':'application/json',Prefer:'return=representation',...(init.headers||{})}})}
export async function GET(req:Request){const id=await uid(req);if(!id)return NextResponse.json({error:'Unauthorized'},{status:401});const [p,e,c]=await Promise.all([rest('profiles?id=eq.'+id+'&select=*'),rest('profile_education?user_id=eq.'+id+'&order=created_at.desc'),rest('career_timeline?user_id=eq.'+id+'&order=start_date.desc.nullslast')]);const profiles=p.ok?await p.json():[];return NextResponse.json({profile:profiles?.[0]||null,education:e.ok?await e.json():[],career:c.ok?await c.json():[]});}
export async function POST(req:Request){const id=await uid(req);if(!id)return NextResponse.json({error:'Unauthorized'},{status:401});const b=await req.json();const errors:string[]=[];
if(b.profile&&typeof b.profile==='object'){const r=await rest('profiles?id=eq.'+id,{method:'PATCH',body:JSON.stringify(b.profile)});if(!r.ok)errors.push('profile: '+await r.text())}
const educations=Array.isArray(b.education)?b.education:(b.education?[b.education]:[]);for(const item of educations){const p={...item,user_id:id};const r=await rest('profile_education',{method:'POST',body:JSON.stringify(p)});if(!r.ok)errors.push('education: '+await r.text())}
const careers=Array.isArray(b.career)?b.career:(b.career?[b.career]:[]);for(const item of careers){const p={...item,user_id:id};const r=await rest('career_timeline',{method:'POST',body:JSON.stringify(p)});if(!r.ok)errors.push('career: '+await r.text())}
if(errors.length)return NextResponse.json({error:errors.join(' | ')},{status:400});return NextResponse.json({ok:true});}
