import { NextResponse } from 'next/server';
export const runtime='nodejs'; export const dynamic='force-dynamic';
const url=process.env.NEXT_PUBLIC_SUPABASE_URL||''; const anon=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||''; const service=process.env.SUPABASE_SERVICE_ROLE_KEY||'';
async function uid(req:Request){const a=req.headers.get('authorization')||'';if(!a.startsWith('Bearer ')||!url||!anon||!service)return null;const r=await fetch(url+'/auth/v1/user',{headers:{apikey:anon,Authorization:a},cache:'no-store'});if(!r.ok)return null;return (await r.json()).id||null}
async function rest(path:string,init:RequestInit={}){return fetch(url+'/rest/v1/'+path,{...init,cache:'no-store',headers:{apikey:service,Authorization:'Bearer '+service,'Content-Type':'application/json',Prefer:'return=representation',...(init.headers||{})}})}
async function jsonOr<T>(r:Response,fallback:T):Promise<T>{try{return r.ok?await r.json():fallback}catch{return fallback}}
export async function GET(req:Request){const id=await uid(req);if(!id)return NextResponse.json({error:'Unauthorized'},{status:401});const [p,e,c]=await Promise.all([rest('profiles?id=eq.'+id+'&select=*'),rest('profile_education?user_id=eq.'+id+'&select=*&order=created_at.desc'),rest('career_timeline?user_id=eq.'+id+'&select=*&order=start_date.desc.nullslast,created_at.desc')]);return NextResponse.json({profile:(await jsonOr<any[]>(p,[]))[0]||null,education:await jsonOr<any[]>(e,[]),career:await jsonOr<any[]>(c,[])},{headers:{'Cache-Control':'no-store, max-age=0'}})}
export async function POST(req:Request){const id=await uid(req);if(!id)return NextResponse.json({error:'Unauthorized'},{status:401});const b=await req.json();const errors:string[]=[];
if(b.profile&&typeof b.profile==='object'){let r=await rest('profiles?id=eq.'+id,{method:'PATCH',body:JSON.stringify({...b.profile,updated_at:new Date().toISOString()})});if(r.ok){const rows=await jsonOr<any[]>(r,[]);if(!rows.length)r=await rest('profiles',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify({id,...b.profile,updated_at:new Date().toISOString()})})}if(!r.ok)errors.push('profile: '+await r.text())}
for(const x of (Array.isArray(b.education)?b.education:(b.education?[b.education]:[]))){const r=await rest('profile_education',{method:'POST',body:JSON.stringify({...x,user_id:id})});if(!r.ok)errors.push('education: '+await r.text())}
for(const x of (Array.isArray(b.career)?b.career:(b.career?[b.career]:[]))){const r=await rest('career_timeline',{method:'POST',body:JSON.stringify({...x,user_id:id})});if(!r.ok)errors.push('career: '+await r.text())}
if(errors.length)return NextResponse.json({error:errors.join(' | ')},{status:400});return NextResponse.json({ok:true},{headers:{'Cache-Control':'no-store, max-age=0'}})}
