-- DrawUp V17 — OPTIONAL: import the firm names that used to be hard-coded on the Connect page.
--
-- Run this ONLY if you want those firms listed in the live directory. It is not required.
-- It inserts each firm as an UNVERIFIED listing with its name (and, for the international
-- firms, the headquarters city/country that was shown before). Nothing else about any
-- firm is invented: no descriptions, people, phone numbers, projects or logos.
-- The 20 made-up U.S. roster names (Atlas & Finch, Ashgrove Partners, Example Studio A …)
-- are deliberately NOT included.
--
-- Additive and idempotent: existing firms with the same slug are left untouched.

with src(name, slug, city, country) as (values
  ('Zaha Hadid Architects', 'zaha-hadid-architects', 'London', 'United Kingdom'),
  ('Foster + Partners', 'foster-and-partners', 'London', 'United Kingdom'),
  ('MVRDV', 'mvrdv', 'Rotterdam', 'Netherlands'),
  ('Snøhetta', 'sn-hetta', 'Oslo', 'Norway'),
  ('Bjarke Ingels Group (BIG)', 'bjarke-ingels-group-big', 'Copenhagen', 'Denmark'),
  ('Herzog & de Meuron', 'herzog-and-de-meuron', 'Basel', 'Switzerland'),
  ('Renzo Piano Building Workshop', 'renzo-piano-building-workshop', 'Genoa', 'Italy'),
  ('David Chipperfield Architects', 'david-chipperfield-architects', 'London', 'United Kingdom'),
  ('Kengo Kuma & Associates', 'kengo-kuma-and-associates', 'Tokyo', 'Japan'),
  ('SANAA', 'sanaa', 'Tokyo', 'Japan'),
  ('Shigeru Ban Architects', 'shigeru-ban-architects', 'Tokyo', 'Japan'),
  ('WOHA', 'woha', 'Singapore', 'Singapore'),
  ('MAD Architects', 'mad-architects', 'Beijing', 'China'),
  ('Bernard Khoury / DW5', 'bernard-khoury-dw5', 'Beirut', 'Lebanon'),
  ('X-ARCHITECTS', 'x-architects', 'Dubai', 'UAE'),
  ('Adjaye Associates', 'adjaye-associates', 'Accra', 'Ghana'),
  ('Counterspace', 'counterspace', 'Johannesburg', 'South Africa'),
  ('Kéré Architecture', 'k-r-architecture', 'Gando', 'Burkina Faso'),
  ('Diamond Schmitt', 'diamond-schmitt', 'Toronto', 'Canada'),
  ('FR-EE / Fernando Romero Enterprise', 'fr-ee-fernando-romero-enterprise', 'Mexico City', 'Mexico'),
  ('ELEMENTAL', 'elemental', 'Santiago', 'Chile'),
  ('Studio MK27', 'studio-mk27', 'São Paulo', 'Brazil'),
  ('Woods Bagot', 'woods-bagot', 'Adelaide', 'Australia'),
  ('Cox Architecture', 'cox-architecture', 'Sydney', 'Australia'),
  ('Gensler', 'gensler', null, null),
  ('Perkins&Will', 'perkinsandwill', null, null),
  ('HKS', 'hks', null, null),
  ('Corgan', 'corgan', null, null),
  ('Populous', 'populous', null, null),
  ('Perkins Eastman', 'perkins-eastman', null, null),
  ('NBBJ', 'nbbj', null, null),
  ('ZGF', 'zgf', null, null),
  ('PGAL', 'pgal', null, null),
  ('KPF', 'kpf', null, null),
  ('HNTB', 'hntb', null, null),
  ('NELSON Worldwide', 'nelson-worldwide', null, null),
  ('IA Interior Architects', 'ia-interior-architects', null, null),
  ('HMC Architects', 'hmc-architects', null, null),
  ('VLK Architects', 'vlk-architects', null, null),
  ('McMillan Pazdan Smith', 'mcmillan-pazdan-smith', null, null),
  ('CannonDesign', 'cannondesign', null, null),
  ('DLR Group', 'dlr-group', null, null),
  ('SmithGroup', 'smithgroup', null, null),
  ('SOM', 'som', null, null),
  ('Ware Malcomb', 'ware-malcomb', null, null),
  ('LPA Design Studios', 'lpa-design-studios', null, null),
  ('HOK', 'hok', null, null),
  ('PBK', 'pbk', null, null),
  ('MOREgroup', 'moregroup', null, null),
  ('BIG – Bjarke Ingels Group', 'big-bjarke-ingels-group', null, null),
  ('KEi Architects', 'kei-architects', null, null),
  ('LS3P', 'ls3p', null, null),
  ('Little Diversified Architectural Consulting', 'little-diversified-architectural-consulting', null, null),
  ('Clark Nexsen', 'clark-nexsen', null, null),
  ('Moseley Architects', 'moseley-architects', null, null),
  ('Hanbury', 'hanbury', null, null),
  ('VMDO Architects', 'vmdo-architects', null, null),
  ('Quinn Evans', 'quinn-evans', null, null),
  ('Page', 'page', null, null),
  ('Lake Flato', 'lake-flato', null, null),
  ('Overland Partners', 'overland-partners', null, null),
  ('KieranTimberlake', 'kierantimberlake', null, null),
  ('Ballinger', 'ballinger', null, null),
  ('EwingCole', 'ewingcole', null, null),
  ('GWWO Architects', 'gwwo-architects', null, null),
  ('Hord Coplan Macht', 'hord-coplan-macht', null, null),
  ('Ayers Saint Gross', 'ayers-saint-gross', null, null),
  ('Shepley Bulfinch', 'shepley-bulfinch', null, null),
  ('Elkus Manfredi Architects', 'elkus-manfredi-architects', null, null),
  ('BKV Group', 'bkv-group', null, null),
  ('Wold Architects and Engineers', 'wold-architects-and-engineers', null, null),
  ('Hoefer Welker', 'hoefer-welker', null, null),
  ('LMN Architects', 'lmn-architects', null, null),
  ('VCBO Architecture', 'vcbo-architecture', null, null),
  ('KZF Design', 'kzf-design', null, null),
  ('STV', 'stv', null, null),
  ('JMT', 'jmt', null, null),
  ('GHD', 'ghd', null, null),
  ('WSP', 'wsp', null, null),
  ('AECOM', 'aecom', null, null),
  ('Stantec', 'stantec', null, null),
  ('HDR', 'hdr', null, null),
  ('Jacobs', 'jacobs', null, null),
  ('Burns & McDonnell', 'burns-and-mcdonnell', null, null),
  ('Arcadis', 'arcadis', null, null),
  ('Kimley-Horn', 'kimley-horn', null, null),
  ('Fluor', 'fluor', null, null),
  ('CallisonRTKL', 'callisonrtkl', null, null),
  ('Leo A Daly', 'leo-a-daly', null, null),
  ('Cooper Carry', 'cooper-carry', null, null),
  ('TVS', 'tvs', null, null),
  ('The Beck Group', 'the-beck-group', null, null),
  ('Mithun', 'mithun', null, null),
  ('GGLO', 'gglo', null, null),
  ('Olson Kundig', 'olson-kundig', null, null),
  ('Mahlum', 'mahlum', null, null),
  ('SRG Partnership', 'srg-partnership', null, null),
  ('Duda|Paine Architects', 'duda-paine-architects', null, null),
  ('Dewberry', 'dewberry', null, null),
  ('Baskervill', 'baskervill', null, null),
  ('Davis Brody Bond', 'davis-brody-bond', null, null),
  ('FXCollaborative', 'fxcollaborative', null, null),
  ('Handel Architects', 'handel-architects', null, null),
  ('Marvel', 'marvel', null, null),
  ('SHoP Architects', 'shop-architects', null, null),
  ('Robert A.M. Stern Architects', 'robert-a-m-stern-architects', null, null),
  ('Selldorf Architects', 'selldorf-architects', null, null),
  ('Ennead Architects', 'ennead-architects', null, null),
  ('Diller Scofidio + Renfro', 'diller-scofidio-and-renfro', null, null),
  ('Steven Holl Architects', 'steven-holl-architects', null, null),
  ('Sasaki', 'sasaki', null, null),
  ('Payette', 'payette', null, null),
  ('NADAAA', 'nadaaa', null, null),
  ('MASS Design Group', 'mass-design-group', null, null),
  ('Goody Clancy', 'goody-clancy', null, null),
  ('CambridgeSeven', 'cambridgeseven', null, null),
  ('Finegold Alexander Architects', 'finegold-alexander-architects', null, null),
  ('Arrowstreet', 'arrowstreet', null, null),
  ('Bruner/Cott Architects', 'bruner-cott-architects', null, null),
  ('Hacin', 'hacin', null, null),
  ('Morris Adjmi Architects', 'morris-adjmi-architects', null, null),
  ('Gresham Smith', 'gresham-smith', null, null),
  ('Goodwyn Mills Cawood', 'goodwyn-mills-cawood', null, null),
  ('Cooper Robertson', 'cooper-robertson', null, null),
  ('Moody Nolan', 'moody-nolan', null, null),
  ('NBBJ Design', 'nbbj-design', null, null),
  ('Mack Scogin Merrill Elam Architects', 'mack-scogin-merrill-elam-architects', null, null),
  ('Lord Aeck Sargent', 'lord-aeck-sargent', null, null),
  ('EskewDumezRipple', 'eskewdumezripple', null, null),
  ('Trahan Architects', 'trahan-architects', null, null),
  ('Manning Architects', 'manning-architects', null, null),
  ('Morris Architects', 'morris-architects', null, null),
  ('Kirksey Architecture', 'kirksey-architecture', null, null),
  ('Pfluger Architects', 'pfluger-architects', null, null),
  ('KAI Enterprises', 'kai-enterprises', null, null),
  ('BRW Architects', 'brw-architects', null, null),
  ('O’Connell Robertson', 'o-connell-robertson', null, null),
  ('Kirksey', 'kirksey', null, null),
  ('Method Architecture', 'method-architecture', null, null),
  ('Studio Red Architects', 'studio-red-architects', null, null),
  ('Marmon Mok', 'marmon-mok', null, null),
  ('Ford, Powell & Carson', 'ford-powell-and-carson', null, null),
  ('Overland', 'overland', null, null),
  ('Michael Hsu Office of Architecture', 'michael-hsu-office-of-architecture', null, null),
  ('Clayton Korte', 'clayton-korte', null, null),
  ('Specht Novak', 'specht-novak', null, null),
  ('Bohlin Cywinski Jackson', 'bohlin-cywinski-jackson', null, null),
  ('Miller Hull Partnership', 'miller-hull-partnership', null, null),
  ('Hennebery Eddy Architects', 'hennebery-eddy-architects', null, null),
  ('Holst Architecture', 'holst-architecture', null, null),
  ('GBD Architects', 'gbd-architects', null, null),
  ('SERA Architects', 'sera-architects', null, null),
  ('Opsis Architecture', 'opsis-architecture', null, null),
  ('Ankrom Moisan', 'ankrom-moisan', null, null),
  ('ZGF Architects', 'zgf-architects', null, null),
  ('Hacker Architects', 'hacker-architects', null, null),
  ('Brooks + Scarpa', 'brooks-and-scarpa', null, null),
  ('Morphosis', 'morphosis', null, null),
  ('Johnston Marklee', 'johnston-marklee', null, null),
  ('Michael Maltzan Architecture', 'michael-maltzan-architecture', null, null),
  ('Frederick Fisher and Partners', 'frederick-fisher-and-partners', null, null),
  ('EYRC Architects', 'eyrc-architects', null, null),
  ('Rios', 'rios', null, null),
  ('Marmol Radziner', 'marmol-radziner', null, null),
  ('KAA Design', 'kaa-design', null, null),
  ('Studio One Eleven', 'studio-one-eleven', null, null),
  ('Carrier Johnson + CULTURE', 'carrier-johnson-and-culture', null, null),
  ('CO Architects', 'co-architects', null, null),
  ('HED', 'hed', null, null),
  ('AC Martin', 'ac-martin', null, null),
  ('Cuningham', 'cuningham', null, null),
  ('Steinberg Hart', 'steinberg-hart', null, null),
  ('WRNS Studio', 'wrns-studio', null, null),
  ('EHDD', 'ehdd', null, null),
  ('Leddy Maytum Stacy Architects', 'leddy-maytum-stacy-architects', null, null),
  ('Fougeron Architecture', 'fougeron-architecture', null, null),
  ('Aidlin Darling Design', 'aidlin-darling-design', null, null),
  ('Feldman Architecture', 'feldman-architecture', null, null),
  ('Skidmore, Owings & Merrill', 'skidmore-owings-and-merrill', null, null),
  ('Solomon Cordwell Buenz', 'solomon-cordwell-buenz', null, null),
  ('Goettsch Partners', 'goettsch-partners', null, null),
  ('Ross Barney Architects', 'ross-barney-architects', null, null),
  ('JGMA', 'jgma', null, null),
  ('Krueck Sexton Partners', 'krueck-sexton-partners', null, null),
  ('Valerio Dewalt Train', 'valerio-dewalt-train', null, null),
  ('Booth Hansen', 'booth-hansen', null, null),
  ('Hartshorne Plunkard Architecture', 'hartshorne-plunkard-architecture', null, null),
  ('Legat Architects', 'legat-architects', null, null),
  ('Cannon Architects', 'cannon-architects', null, null),
  ('Ratio Architects', 'ratio-architects', null, null),
  ('Schmidt Associates', 'schmidt-associates', null, null),
  ('Blackburn Architects', 'blackburn-architects', null, null),
  ('Davis Architects', 'davis-architects', null, null),
  ('ESa', 'esa', null, null),
  ('Tuck-Hinton Architecture & Design', 'tuck-hinton-architecture-and-design', null, null),
  ('Centric Architecture', 'centric-architecture', null, null),
  ('Hastings Architecture', 'hastings-architecture', null, null),
  ('Earl Swensson Associates', 'earl-swensson-associates', null, null),
  ('Fentress Architects', 'fentress-architects', null, null),
  ('Tryba Architects', 'tryba-architects', null, null),
  ('Davis Partnership Architects', 'davis-partnership-architects', null, null),
  ('Semple Brown Design', 'semple-brown-design', null, null),
  ('Roth Sheppard Architects', 'roth-sheppard-architects', null, null),
  ('Anderson Mason Dale Architects', 'anderson-mason-dale-architects', null, null),
  ('OZ Architecture', 'oz-architecture', null, null),
  ('Merrick & Company', 'merrick-and-company', null, null),
  ('Cushing Terrell', 'cushing-terrell', null, null),
  ('CTA Architects Engineers', 'cta-architects-engineers', null, null),
  ('JLG Architects', 'jlg-architects', null, null),
  ('BWBR', 'bwbr', null, null),
  ('HGA', 'hga', null, null),
  ('Snow Kreilich Architects', 'snow-kreilich-architects', null, null),
  ('MSR Design', 'msr-design', null, null),
  ('RSP Architects', 'rsp-architects', null, null),
  ('Pope Design Group', 'pope-design-group', null, null),
  ('LHB', 'lhb', null, null)
),
ins as (
  insert into public.firms (slug, name, is_verified, is_demo)
  select slug, name, false, false from src
  on conflict (slug) do nothing
  returning id, slug
)
insert into public.firm_offices (firm_id, city, country, is_headquarters)
select ins.id, src.city, src.country, true
from ins join src on src.slug = ins.slug
where src.city is not null;
