-- DrawUp V20 personal Arch Coach (My Player style coach). Additive and idempotent.
-- Same content as drawup-v20-coach-01..05.sql in the v20 coach-sql deliverables.

-- ===== drawup-v20-coach-01.sql
-- DrawUp V20 personal Arch Coach, file 1 of 5: tables.
-- Additive and idempotent. Creates new tables only. Nothing is dropped or rewritten.

-- The 14 skills on the Arch Coach card, in display order.
create or replace function public.arch_coach_skill_keys()
returns text[] language sql immutable as $$
  select array['design','render','space_planning','research','precedents','problem_solving',
    'code_compliance','accessibility','materials','curiosity','details','documentation','advice','presentation']
$$;

-- Starting archetype: College Professor, balanced ratings in the 60s and low 70s (914 points).
create or replace function public.arch_coach_default_skills()
returns jsonb language sql immutable as $$
  select '{"design":66,"render":60,"space_planning":64,"research":72,"precedents":70,"problem_solving":68,"code_compliance":64,"accessibility":62,"materials":62,"curiosity":70,"details":62,"documentation":64,"advice":68,"presentation":62}'::jsonb
$$;

-- Point budget grows with XP but is capped well below 14 x 99 (1386), so maxing every skill is impossible.
create or replace function public.arch_coach_budget(p_xp integer)
returns integer language sql immutable as $$
  select least(1190, 920 + greatest(coalesce(p_xp, 0), 0) / 20)
$$;

create or replace function public.arch_coach_level(p_xp integer)
returns integer language sql immutable as $$
  select 1 + floor(sqrt(greatest(coalesce(p_xp, 0), 0) / 25.0))::integer
$$;

create table if not exists public.arch_coach_legends (
  key text primary key,
  name text not null,
  kind text not null default 'architect',
  principles text[] not null default '{}',
  note text,
  xp_required integer not null default 100,
  sort_order integer not null default 100,
  constraint arch_coach_legends_kind_check check (kind in ('architect', 'engineer'))
);

create table if not exists public.arch_coach_profiles (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  mode text,
  appearance jsonb not null default '{}'::jsonb,
  discipline text not null default 'Architecture',
  focus text not null default 'Design',
  archetype text not null default 'College Professor',
  answer_style text not null default 'balanced',
  skills jsonb not null default public.arch_coach_default_skills(),
  legend text references public.arch_coach_legends(key) on delete set null,
  language text not null default 'auto',
  xp integer not null default 0,
  prompt_answered_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint arch_coach_profiles_mode_check check (mode is null or mode in ('custom', 'generic', 'later')),
  constraint arch_coach_profiles_style_check check (answer_style in ('concise', 'balanced', 'in_depth')),
  constraint arch_coach_profiles_lang_check check (language in ('auto','en','es','fr','pt','zh','ar','hi','de','ja','ko','tl','vi','it')),
  constraint arch_coach_profiles_text_len check (char_length(discipline) <= 60 and char_length(focus) <= 60 and char_length(archetype) <= 60),
  constraint arch_coach_profiles_appearance_check check (jsonb_typeof(appearance) = 'object' and char_length(appearance::text) <= 2000),
  constraint arch_coach_profiles_xp_check check (xp >= 0)
);

-- XP ledger: one row per earning event. The unique key stops the same event from counting twice.
create table if not exists public.arch_coach_xp_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  kind text not null,
  ref_id text not null,
  points integer not null,
  created_at timestamptz not null default now(),
  constraint arch_coach_xp_events_once unique (user_id, kind, ref_id)
);

create index if not exists arch_coach_xp_events_user_idx on public.arch_coach_xp_events (user_id, kind, created_at desc);

select 'DONE drawup-v20-coach-01' as status;
-- END

-- ===== drawup-v20-coach-02.sql
-- DrawUp V20 personal Arch Coach, file 2 of 5: Inspiration Legends.
-- Three short, publicly documented principle words and one factual line each. No portraits, no quotes.
-- Safe to run twice: rows are upserted by key.

insert into public.arch_coach_legends (key, name, kind, principles, note, xp_required, sort_order) values
  ('paul-r-williams', 'Paul R. Williams', 'architect', array['Elegance','Client empathy','Perseverance'],
   'Los Angeles architect who became the first Black member of the American Institute of Architects in 1923.', 50, 10),
  ('julia-morgan', 'Julia Morgan', 'architect', array['Craftsmanship','Reinforced concrete','Client focus'],
   'First woman licensed as an architect in California and designer of Hearst Castle. AIA Gold Medal 2014.', 100, 20),
  ('frank-lloyd-wright', 'Frank Lloyd Wright', 'architect', array['Organic design','Harmony with site','Open plan'],
   'American architect of Fallingwater and the Solomon R. Guggenheim Museum in New York.', 150, 30),
  ('norma-merrick-sklarek', 'Norma Merrick Sklarek', 'architect', array['Technical rigor','Project delivery','Mentorship'],
   'First Black woman licensed as an architect in New York (1954) and California (1962).', 200, 40),
  ('ove-arup', 'Ove Arup', 'engineer', array['Total design','Integration','Humane engineering'],
   'Anglo-Danish structural engineer who founded Arup and argued for total design across disciplines.', 250, 50),
  ('i-m-pei', 'I. M. Pei', 'architect', array['Geometric clarity','Light','Modernism'],
   'Chinese-American architect of the Louvre Pyramid in Paris. Pritzker Architecture Prize 1983.', 300, 60),
  ('fazlur-rahman-khan', 'Fazlur Rahman Khan', 'engineer', array['Structural efficiency','Tube systems','Collaboration'],
   'Structural engineer behind the tube systems of the John Hancock Center and the Sears (Willis) Tower in Chicago.', 350, 70),
  ('emily-warren-roebling', 'Emily Warren Roebling', 'engineer', array['Persistence','Technical fluency','Coordination'],
   'Carried day to day engineering coordination of the Brooklyn Bridge after Washington Roebling fell ill.', 400, 80),
  ('tadao-ando', 'Tadao Ando', 'architect', array['Concrete','Light','Simplicity'],
   'Self-taught Japanese architect known for exposed concrete and light. Pritzker Architecture Prize 1995.', 450, 90),
  ('zaha-hadid', 'Zaha Hadid', 'architect', array['Vision','Fluidity','Innovation'],
   'Iraqi-British architect and the first woman to receive the Pritzker Architecture Prize, in 2004.', 500, 100)
on conflict (key) do update set
  name = excluded.name, kind = excluded.kind, principles = excluded.principles,
  note = excluded.note, xp_required = excluded.xp_required, sort_order = excluded.sort_order;

select 'DONE drawup-v20-coach-02' as status;
-- END

-- ===== drawup-v20-coach-03.sql
-- DrawUp V20 personal Arch Coach, file 3 of 5: the guard trigger.
-- NOTE: this file uses one plpgsql function (a trigger has to be plpgsql). Run the whole file at once.
-- Every save is checked in the database, so the page cannot be bypassed:
--   all 14 skills present, whole numbers 25..99, total within the XP point budget,
--   and an adopted legend must already be unlocked by the member XP.

create or replace function public.arch_coach_profiles_guard()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  k text;
  v numeric;
  total integer := 0;
  need integer;
begin
  if new.skills is null or jsonb_typeof(new.skills) <> 'object' then
    raise exception 'Arch Coach skills must be a set of ratings';
  end if;
  if (select count(*) from jsonb_object_keys(new.skills)) <> cardinality(arch_coach_skill_keys()) then
    raise exception 'Arch Coach needs exactly the 14 skills';
  end if;
  foreach k in array arch_coach_skill_keys() loop
    if jsonb_typeof(new.skills -> k) is distinct from 'number' then
      raise exception 'Arch Coach skill % is missing', k;
    end if;
    v := (new.skills ->> k)::numeric;
    if v < 25 or v > 99 or mod(v, 1) <> 0 then
      raise exception 'Arch Coach skill % must be a whole number from 25 to 99', k;
    end if;
    total := total + v::integer;
  end loop;
  if total > arch_coach_budget(new.xp) then
    raise exception 'Arch Coach skills use % points but your budget is % (earn XP to grow it)', total, arch_coach_budget(new.xp);
  end if;
  if new.legend is not null then
    select xp_required into need from arch_coach_legends where key = new.legend;
    if need is null then
      raise exception 'Unknown legend';
    end if;
    if new.xp < need then
      raise exception 'That legend unlocks at % XP', need;
    end if;
  end if;
  if tg_op = 'UPDATE' and new.xp < old.xp then
    new.xp := old.xp;
  end if;
  if new.mode is not null and new.prompt_answered_at is null then
    new.prompt_answered_at := now();
  end if;
  new.updated_at := now();
  return new;
end
$$;

drop trigger if exists arch_coach_profiles_guard on public.arch_coach_profiles;
create trigger arch_coach_profiles_guard
  before insert or update on public.arch_coach_profiles
  for each row execute function public.arch_coach_profiles_guard();

select 'DONE drawup-v20-coach-03' as status;
-- END

-- ===== drawup-v20-coach-04.sql
-- DrawUp V20 personal Arch Coach, file 4 of 5: row level security and column grants.
-- Members read and edit only their own coach. XP is never writable from the browser:
-- the xp column is left out of the insert and update grants, and the XP ledger is read only.

alter table public.arch_coach_profiles enable row level security;
alter table public.arch_coach_xp_events enable row level security;
alter table public.arch_coach_legends enable row level security;

revoke all on public.arch_coach_profiles from anon, authenticated;
revoke all on public.arch_coach_xp_events from anon, authenticated;
revoke all on public.arch_coach_legends from anon, authenticated;

grant select on public.arch_coach_profiles to authenticated;
grant insert (user_id, mode, appearance, discipline, focus, archetype, answer_style, skills, legend, language)
  on public.arch_coach_profiles to authenticated;
grant update (mode, appearance, discipline, focus, archetype, answer_style, skills, legend, language)
  on public.arch_coach_profiles to authenticated;
grant select on public.arch_coach_xp_events to authenticated;
grant select on public.arch_coach_legends to anon, authenticated;

drop policy if exists arch_coach_profiles_own_select on public.arch_coach_profiles;
create policy arch_coach_profiles_own_select on public.arch_coach_profiles
  for select to authenticated using (user_id = auth.uid());

drop policy if exists arch_coach_profiles_own_insert on public.arch_coach_profiles;
create policy arch_coach_profiles_own_insert on public.arch_coach_profiles
  for insert to authenticated with check (user_id = auth.uid() and xp = 0);

drop policy if exists arch_coach_profiles_own_update on public.arch_coach_profiles;
create policy arch_coach_profiles_own_update on public.arch_coach_profiles
  for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists arch_coach_xp_events_own_select on public.arch_coach_xp_events;
create policy arch_coach_xp_events_own_select on public.arch_coach_xp_events
  for select to authenticated using (user_id = auth.uid());

drop policy if exists arch_coach_legends_read on public.arch_coach_legends;
create policy arch_coach_legends_read on public.arch_coach_legends
  for select to anon, authenticated using (true);

grant execute on function public.arch_coach_budget(integer) to anon, authenticated;
grant execute on function public.arch_coach_level(integer) to anon, authenticated;
grant execute on function public.arch_coach_skill_keys() to anon, authenticated;
grant execute on function public.arch_coach_default_skills() to anon, authenticated;

select 'DONE drawup-v20-coach-04' as status;
-- END

-- ===== drawup-v20-coach-05.sql
-- DrawUp V20 personal Arch Coach, file 5 of 5: earning XP (server side only).
-- NOTE: the two Connect trigger functions are plpgsql. Run the whole file at once.
-- award_arch_coach_xp can only be called with the service role (the DrawUp server) or by these triggers.
-- Each event counts once (ledger unique key) and each kind has a daily cap.
--   ask 5 (20 a day), upload 8 (10), check 15 (10), peer_like 2 (25), peer_comment 4 (25), board_help 6 (10)

create or replace function public.award_arch_coach_xp(p_user_id uuid, p_kind text, p_ref text)
returns integer language sql volatile security definer set search_path = public as $$
  with cfg as (
    select case p_kind when 'ask' then 5 when 'upload' then 8 when 'check' then 15
             when 'peer_like' then 2 when 'peer_comment' then 4 when 'board_help' then 6 else 0 end as pts,
           case p_kind when 'ask' then 20 when 'upload' then 10 when 'check' then 10
             when 'peer_like' then 25 when 'peer_comment' then 25 when 'board_help' then 10 else 0 end as cap
  ), ok as (
    select pts from cfg
     where pts > 0 and p_user_id is not null and length(trim(coalesce(p_ref, 'x'))) > 0
       and exists (select 1 from profiles where id = p_user_id)
       and (select count(*) from arch_coach_xp_events e
             where e.user_id = p_user_id and e.kind = p_kind and e.created_at > now() - interval '1 day') < cap
  ), ins as (
    insert into arch_coach_xp_events (user_id, kind, ref_id, points)
    select p_user_id, p_kind, left(p_ref, 200), pts from ok
    on conflict (user_id, kind, ref_id) do nothing
    returning points
  ), up as (
    insert into arch_coach_profiles (user_id, xp)
    select p_user_id, points from ins
    on conflict (user_id) do update set xp = arch_coach_profiles.xp + excluded.xp
    returning xp
  )
  select coalesce((select points from ins), 0)
$$;

revoke all on function public.award_arch_coach_xp(uuid, text, text) from public, anon, authenticated;
grant execute on function public.award_arch_coach_xp(uuid, text, text) to service_role;

-- Peer collecting: a like from another member on your Connect post.
create or replace function public.arch_coach_xp_on_like()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  owner uuid;
begin
  select author_id into owner from connect_posts where id = new.post_id;
  if owner is not null and owner <> new.user_id then
    perform award_arch_coach_xp(owner, 'peer_like', new.post_id::text || ':' || new.user_id::text);
  end if;
  return new;
exception when others then
  return new;
end
$$;

-- A reply from another member on your post, and helping someone on Boards.
create or replace function public.arch_coach_xp_on_comment()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  owner uuid;
  post_kind text;
begin
  select author_id, kind into owner, post_kind from connect_posts where id = new.post_id;
  if owner is not null and owner <> new.author_id then
    perform award_arch_coach_xp(owner, 'peer_comment', new.post_id::text || ':' || new.author_id::text);
    if post_kind = 'board' then
      perform award_arch_coach_xp(new.author_id, 'board_help', new.post_id::text);
    end if;
  end if;
  return new;
exception when others then
  return new;
end
$$;

revoke all on function public.arch_coach_xp_on_like() from public, anon, authenticated;
revoke all on function public.arch_coach_xp_on_comment() from public, anon, authenticated;

drop trigger if exists arch_coach_xp_like on public.connect_likes;
create trigger arch_coach_xp_like after insert on public.connect_likes
  for each row execute function public.arch_coach_xp_on_like();

drop trigger if exists arch_coach_xp_comment on public.connect_comments;
create trigger arch_coach_xp_comment after insert on public.connect_comments
  for each row execute function public.arch_coach_xp_on_comment();

select 'DONE drawup-v20-coach-05' as status;
-- END
